### ISSUE TITLE
3.0.0: Ninja's shutdown callbacks are not invoked: services are not disposed

### ISSUE THREAD

**Issue by nobullet** [ninjaframework/ninja#145]
NinjaServletListener.contextDestroyed is not invoked when the server stops: 
both standalone and ninja plugin mode.

mvn: 3.1.1
java "1.7.0_51"

**Comment by raphaelbauer** [comment]
I just tried it. And it's not the case for me... contextDestroyed is always executed; everything works as expected. 
Can you give an example - maybe an example repository where this happens?

**Comment by nobullet** [comment]
For some reason newly created project behaves in this way: 
standalone mode and maven plugin are not stopped correctly: JVM stops abruptly when CTRL+C or kill -SIGTERM {pid}.
But mvn jetty:run works and JVM is stopped correctly.

Take a look at my repo with newly created service lifecycle example with @Start/@Dispose methods. 

https://github.com/nobullet/ninja-3.0.0-service-start-stop

services.ServiceExample produces log messages when starts and stops.

**Comment by raphaelbauer** [comment]
Hi nobullet,

now I see what you mean.

afaics there are two problems:
1) In standalone mode there is no shutdown hook attached. Therefore the @Dispose methods are not called. That's the root issue. 
2) Ninja:run mode does not work because of 1).
3) In testcases everything is fine and wired up correctly.

I fixed the issue. But there is one thing. If you run ninja:run everything is disposed correctly - BUT you may not get the complete output if you write something on system.out.

Can you verify if https://github.com/ninjaframework/ninja/tree/145-shutdown-hooks-not-executed fixes the issue for you?

Cheers,

Raphael

**Comment by nobullet** [comment]
Hi Raphael.

I confirm that this CL fixes the problem.
I am able to check shutdown by logging into the file:

https://github.com/nobullet/ninja-3.0.0-service-start-stop/blob/master/src/main/java/logback.xml

Thank you for the fix.

**Comment by raphaelbauer** [comment]
KK. I'll merge the branch. Thanks for the report :)
