### ISSUE TITLE
Glassfish deployment yields org.jboss.weld.exceptions.DeploymentException

### ISSUE THREAD

**Issue by melgin** [ninjaframework/ninja#181]
When I try to packaged war file to Glassfish 4.0, I get following error message:

Exception while loading the app : CDI deployment failure:WELD-001408 Unsatisfied dependencies for type [Logger] with qualifiers [@Default] at injection point [[BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject public ninja.utils.ResultHandler(Logger, TemplateEngineManager)]

**Comment by raphaelbauer** [comment]
Hmm. I know that some people are using Ninja on a JBoss 6.1 EAP. There it works. What the exception tells you is that Glassfish does not know how to generate a java.util.logging.Logger. Apart from the fact that "java.util.logging.Logger" is wrong (it should be the slf4j logger) the error is a bad sign, because the whole injection should be peformed by Guice and not by Glassfish's Weld.

Not sure how to fix that for Glassfish. But it would be really cool to know. 

I'll fix the "wrong" logger in Ninja. But I am sure this won't make Ninja run on Glassfish 4.0 though...

**Comment by raphaelbauer** [comment]
Hmm. One more idea... ResultHandler is using javax.inject.Inject annotation and not com.google.guice.Inject as @Inject above the constructor. This causes Weld to try the injection and ultimately causes the error.

**Comment by raphaelbauer** [comment]
The latest develop no longer uses any org.inject.Inject annotations. This should relax the issue even more. Any feedback would be really cool if you are still interested. I'll fix the issue for now.
