### ISSUE TITLE
URLs that end in / are not matched 

### ISSUE THREAD

**Issue by mikehearn** [ninjaframework/ninja#288]
GET().route("/foo") ....    does not match /foo/ 

I have had a few bug reports on my site because of this. People expect a trailing slash to make no difference.

What's the best fix - to remove a trailing slash at match time, or to include (|/)$ at the end of the regex that Route produces?

**Comment by raphaelbauer** [comment]
One question from me would be why people are using both uris in your service. Who told them to do so? Usually /foo and /foo/ are two different resources in terms of the web, and treating them as the same may/or me not be the right approach. A SEO sensitive approach would be to forward the uris to the correct one, so that the search engines know what the "correct" one is.

Short answer: If you really want to treat both uris the same I'd use a regex in your routes :)

Btw - For what service are you using Ninja for?

**Comment by raphaelbauer** [comment]
btw: That may be related: https://github.com/ninjaframework/ninja/pull/241#issuecomment-70951237

**Comment by mikehearn** [comment]
Hmm, fair enough I guess. I had a URL in my web app that had a trailing slash for some reason and I was just surprised it didn't work. I guess URL spaces are not actually like directories in this regard :)
