### ISSUE TITLE
Error page not working in Production mode

### ISSUE THREAD

**Issue by h4ck4life** [ninjaframework/ninja#291]
Hi, 

I've a problem where default error page for example, 404notFound.ftl.html is working okay in SuperDevMode (mvn ninja:run) but not okay if running in production mode (java -Dninja.mode=prod -Dninja.port=8080 -jar target/whatever.jar) , it will return the default ninja 404 sad face. 

Ninja ver 4.0.4.

No additional code to reproduce, just switch between SuperDevMode and Production and navigate to any not found url can see the different. 

Thanks,
Alif

**Comment by raphaelbauer** [comment]
I can verify that this is happening when assembling the jar via "mvn clean compile assembly:single". It's not happening when creating the war via "mvn war:war".

**Comment by raphaelbauer** [comment]
A solution is to use the maven shade plugin.

First of all change the <packagin> from "war" to "jar"

Then add the shade plugin like so:

```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>ninja.standalone.NinjaJetty</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

Generation of the fat jar is done via "mvn package"

Let us know if that works, then we can change the archetypes and update the documentation accordingly.

**Comment by h4ck4life** [comment]
Thanks Raphael for the reply. I've tried your post above, still seeing default sad face error. Probably my pom.xml is configured incorrectly, here it is > https://gist.github.com/h4ck4life/373adb1b2c87907fd024

**Comment by h4ck4life** [comment]
Hi Raphael,

Just to update that your solution above > https://github.com/ninjaframework/ninja/issues/291#issuecomment-72021218 is working fine now on my end! I could see my custom error page now, no more default sad face page.
- change from 'war' to 'jar' in pom.xml
- add the shade plugin as stated aboved in your post.
- mvn package
- run the generated jar -> e.g. ( java -Dninja.mode=prod -Dninja.port=8080 -jar target/xxxx-1.0-SNAPSHOT.jar )

Thanks so much.

**Comment by raphaelbauer** [comment]
Hey Alif, 

the bug is not yet fixed, because the documentation and the archetypes still use the maven-assembly plugin which does not do what we want.

So we have to 
- Remove Maven assembly plugin from all archetypes and potentially integration tests and replace it with the shade plugin (as described above)
- Update the documentation

That will fix the issue. It's not that complicated actually. Would you be interested to contribute the fix?

Thanks,

Raphael

**Comment by h4ck4life** [comment]
Hi Raphael,

Sure I'm glad to contribute make the changes! Let me know how can I start.

**Comment by bazi** [comment]
Hi @h4ck4life, first of all have a look at [How to contribute](http://www.ninjaframework.org/developer/getting_started.html) page.
Then you just fork off from this repository, do your changes in your fork, and after you finish create pull request.

**Comment by h4ck4life** [comment]
@bazi awesome, thanks for the info :)

**Comment by raphaelbauer** [comment]
I think a fix should include the following: 
1) We should replace the assembly plugin in all relevant pom.xml files. (And we should make sure to add a simple xml comment to remind users that they have to switch the project type to "jar" to make that work).
2) Update the website / documentation (in ninja-core/src/site...) to tell the users how to generate the jar file with the shade plugin
..
That's it already... :)

**Comment by thibaultmeyer** [comment]
Hi,

this issue is more complex and can't be simply fixed by modifying the pom.xml file. When compiled on windows, everything works very well (even in production mode) but on Linux (tested on CentOS 7), the default 404 sad face page is used.

Compilation chain : `mvn clean compile assembly:single`

Run command :  `java -Dninja.mode=prod -Dninja.port=8080 -jar target/test404-1.0-SNAPSHOT.jar`

Ninja Version: `4.0.6`

**Compilation:** Windows 8.1 x64 / Java 1.8.0_40 x64 / Maven 3.2.5
**Run:** Windows 8.1 x64 / Java 1.8.0_40 x64 / Maven 3.2.5
**Result:** Custom 404 page works

**Compilation:** Windows 8.1 x64 / Java 1.8.0_40 x64 / Maven 3.2.5
**Run:** CentOS 7 x64 / Java 1.8.0_40 x64 / Maven 3.2.5
**Result:** Custom 404 page works

**Compilation:** CentOS 7 x64 / Java 1.8.0_40 x64 / Maven 3.2.5
**Run:** CentOS 7 x64 / Java 1.8.0_40 x64 / Maven 3.2.5
**Result:** Custom 404 does not works

**Compilation:** CentOS 7 x64 / Java 1.8.0_40 x64 / Maven 3.2.5
**Run:** Windows 8.1 x64 / Java 1.8.0_40 x64 / Maven 3.2.5
**Result:** Custom 404 does not works

**Comment by raphaelbauer** [comment]
I see you are calling mvn clean compile assembly:single. That way you are still using the broken assembly plugin to do the job.

Make sure you call mvn package to create the jar. That way it should work (see comment from 29th Jan).

**Comment by 0xbaadf00d** [comment]
Ok is the assembly plugin not working correctly on Linux, not Ninja.  I will try the workaround.

**Comment by thibaultmeyer** [comment]
Ok is the assembly plugin not working correctly on Linux, not Ninja. I will try the workaround. In the next version of Ninja; "maven-shade-plugin" will be added by default ?

**Comment by raphaelbauer** [comment]
Would you like to contribute the changes for the next version? Should not be too complicated.
1) Plugin has to be added to the two archetypes.
2) Documentation has to be updated. It should describe how to use the plugin (especially changing the packaging from war to jar).

That should it be already...

**Comment by thibaultmeyer** [comment]
Of course, I will try to add this modification on the archetype "ninja-servlet-archetype-simple" and "ninja-servlet-jpa-blog-archetype". The documentation is on another repos ?

**Comment by raphaelbauer** [comment]
This would be great!

**Comment by magikid** [comment]
It looks as though this issue has been resolved by the merge and the issue can be closed.

**Comment by raphaelbauer** [comment]
👍 Thanks!
