### ISSUE TITLE
Error 400 not handled

### ISSUE THREAD

**Issue by thibaultmeyer** [ninjaframework/ninja#336]
Hi

I think the error 400 are not handled by Ninja, i have created a custom template _400badRequest.ftl.html_ (http://www.ninjaframework.org/documentation/basic_concepts/error_handling.html) but when i trigger a 400 error, nothing appear on my browser.

 Developer tool (Chrome CTRL+ALT+i)  show a 400 bad request response but the body is empty.

You can reproduce this issue by just calling the url http://127.0.0.1:8080/%%%%  and on another website : http://ninjaframework.org/%%%%.

Ninja version: `4.0.6`
Java version: `1.8.0 u40 x64`
Operating System: `Windows 8.1 x64`

```
12:00:53.193 [qtp760563749-17] WARN  org.eclipse.jetty.server.HttpChannel - Failed UTF-8 decode for request path, trying ISO-8859-1
12:00:53.193 [qtp760563749-17] WARN  org.eclipse.jetty.http.HttpParser - badMessage: java.lang.NumberFormatException: %% for HttpChannelOverHttp@329eff46{r=0,c=false,a=IDLE,uri=-}
```

**Comment by raphaelbauer** [comment]
That's the intended behavior. Results does allow you to create a custom result from scratch - but it won't take into account your defaults. In order to do so make sure you @Inject Ninja ninja and then get the restult by calling ninja.getXYZResult(...).

If that's not clear we may have to improve the api...

**Comment by thibaultmeyer** [comment]
hmm ok, the page http://www.ninjaframework.org/documentation/custom_routing.html give more information about errors handling.

Thanks
