### ISSUE TITLE
Creating firts app does not work.

### ISSUE THREAD

**Issue by khmarbaise** [ninjaframework/ninja#352]
I have tried to create the first app based on the explanations on this page:

http://www.ninjaframework.org/documentation/getting_started/create_your_first_application.html
but unfortunately it produces a failure during packaging via mvn package:
Could not resolve dependencies for project whatever:first-web:jar:1.0-SNAPSHOT: Failure to find org.terracotta.internal:statistics:jar:1.0.2

This is caused by the terracotta part which is not part of maven central which produces the problem. You should enhance the documentation that a supplemental repository needed to be configured.

**Comment by raphaelbauer** [comment]
Hi khmarbaise,

actually we were re-organizing the dependencies some time ago. After that another user also reported the issue (https://github.com/ninjaframework/ninja/pull/318). Unfortunately nobody else reported the issue, and it does also not happen for a lot of Ninja real life projects - it also does not happen on jenkins-ci (which is a clean build).

One way for us to circumvent the problem is to revert the ehcache changes of pull/318 - but the downside is that this will make our footprint larger with stuff we don't need...

I actually hate that kind of flakiness. On the other hand - afaics there is no better qualified person than you to recommend something. What would you do if Ninja was your project?

Sorry for the inconveniences,

Raphael

**Comment by raphaelbauer** [comment]
@jjlauer and @svenkubiak that discussion might be interesting for you as well :)

**Comment by raphaelbauer** [comment]
Because the problem does not happen here I only can guess... But one idea could be to use

```
            <dependency>
                <groupId>net.sf.ehcache</groupId>
                <artifactId>ehcache-core</artifactId>
                <version>2.6.11</version>
            </dependency>
```

Which also only pulls in core dependencies and is not the .internal one (ok? @jjlauer). Which may be better... But I'd need feedback whether that fixes the issue @svenkubiak and @khmarbaise are seeing... Thanks!

**Comment by khmarbaise** [comment]
The problem is located based on the ninja-core part which contains the reference to ehcache-core-internal:
I have checked via mvn dependency:tree -DoutputFile=result.tree (excerpt put here):

```
|  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.5.1:compile
|  |  \- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
|  +- net.sf.ehcache.internal:ehcache-core:jar:2.9.1:compile
|  |  \- org.terracotta.internal:statistics:jar:1.0.2:compile
|  +- net.spy:spymemcached:jar:2.11.6:compile
|  +- com.googlecode.flyway:flyway-core:jar:2.3.1:compile
```

which contains the org.terracotta.internal dependency. I have taken a look into central http://search.maven.org/#search|ga|1|net.sf.ehcache.internal but this [also contains a reference to terracotta](https://repo1.maven.org/maven2/net/sf/ehcache/internal/ehcache-core/2.10.0/ehcache-core-2.10.0.pom) and will not solve the problem..if you update to a new version of ehcache-core nor ehcache-internal...

**Comment by raphaelbauer** [comment]
Stupid question maybe - but can you give me a pointer why the problem happens for you, but not for me nor on jenkins? Neither I, nor jenkins does have a special config to find that dependency... I just want to understand what is going on... Thanks...

**Comment by raphaelbauer** [comment]
afaics

``` <dependency>
                <groupId>net.sf.ehcache</groupId>
                <artifactId>ehcache-core</artifactId>
                <version>2.6.11</version>
            </dependency>
```

does not have the offending org.terracotta.internal - so we should switch I guess...

**Comment by svenkubiak** [comment]
AFAIK...
The problem comes from a transetive dependecy from ehcache-core to org.terracotta.internal:statistics:jar:1.0.1. This dependency is not hosted in on maven-central-alike (?) repository. The default maven configuration just ignores that, and fetches the dependency. Therefore it works localy with default maven configuraiton and in jenkins. If you have, like in my case, a proxied repository with e.g. Nexus, there is a policy that rejects fetching from non maven-central-alike (?) repositories.

**Comment by raphaelbauer** [comment]
I propose https://github.com/ninjaframework/ninja/pull/353. 353 no longer references org.terracotta.internal:statistics and should fix the issue. 

Would be cool if someone hit by the the issue confirm the fix. And it would be nice if @jjlauer could confirm whether that works in regard to creating a minimal jar file (that was the intention to switch to ehcache.internal in the first place). Thanks for bringing up the issue!

**Comment by raphaelbauer** [comment]
Merged the fix. Thanks for the report!

**Comment by khmarbaise** [comment]
After i have changed to 5.1.2 of ninjaframework with no access to terracotta repository it works perfectly. Thanks. Apart from that the access to the needed terracotta repository seemed to be blocked.
