### ISSUE TITLE
Chinese encoding with utf-8 feel terrible！

### ISSUE THREAD

**Issue by JavaProgrammerLB** [ninjaframework/ninja#357]
When I write Chinese in **messages.properties** ;What I want is "Java忍者" but I get a String like :"Java\u5FCD\u8005".What is the matter?

**Comment by raphaelbauer** [comment]
Can you post more information? How does your messages.properties file look like? Can you attach it? Thanks!

**Comment by metacity** [comment]
This is probably because your IDE treats `.properties` files as ["Java properties files"](http://en.wikipedia.org/wiki/.properties) which are specified to use ISO-8859-1 encoding. And your IDE conforms to the spec by escaping UTF-8 characters. In NetBeans I got around this by setting NetBeans to treat `.properties` as text/plain (Options -> Miscellaneous -> Files -> Choose "properties" extension -> MIME to text/plain).

**Comment by JavaProgrammerLB** [comment]
> raphaelbauer

I use eclipse to ‘Create your first ninja application’ as the website said,when I write Chinese in **messages.properties**,it became to ISO-8859-1,as metacity said ,I Changed my IDE and I can write Chinese.
Can we do something to change the way eclipse treate properties file without hand change.

> metacity
> yes,you are right

**Comment by raphaelbauer** [comment]
Cool - thanks @metacity !

@JavaProgrammerLB - could you close the ticket if your problem is fixed? Thanks!
