### ISSUE TITLE
Multiple methods with annotated routes

### ISSUE THREAD

**Issue by davidgiga1993** [ninjaframework/ninja#362]
When using ninja-jaxy-routes for creating routes it is not possible to assign multiple methods to the same function.
Example:

``` java
@Transactional
@Path("/create/user")
@POST
@GET
public Result addUser(Context context)
{}
```

Only the route for the first method (post) will be applied, the other (get) will return a 404 route not found.
When adding the routes via java code both routes are applied:

``` java
router.POST().route("/create/user").with(AdminController.class, "addUser");
router.GET().route("/create/user").with(AdminController.class, "addUser");
```

Can anyone confirm this issue?

**Comment by raphaelbauer** [comment]
I am not entirely sure without a look at the source code. @gitblit - do you know more about whether that's a bug or a feature?

**Comment by gitblit** [comment]
Jaxy-routes was written to support one http method per registered controller method.  It's neither a bug nor a feature - it was a design constraint.

My first reaction is _this_ is a bug:

``` java
router.POST().route("/create/user").with(AdminController.class, "addUser");
router.GET().route("/create/user").with(AdminController.class, "addUser");
```

To my mind the only value in the following design is reducing the number of method signatures in the controller class at the expense of clarity.

``` java
@Transactional
@Path("/create/user")
@POST
@GET
public Result addUser(Context context)
{
  if (GET) {
  } else {
  }
}
```

I find the intent of this approach much more clear:

``` java
@Path("/create/user")
@GET
public Result viewAddUser(Context context)
{ }

@Transactional
@Path("/create/user")
@POST
public Result addUser(Context context)
{ }
```

IMO controller methods should not be mini-routers/http-method dispatchers; Ninja already has a Router.

Is in-controller method dispatching something you require?  Or are you asking because you found an inconsistency in the rules between manual registration and annotated registration?

**Comment by davidgiga1993** [comment]
Indeed, the last approach is more clear but I find myself redirecting a lot when I want to use the same template for both requests. I know I could just explicit use the template from the "viewAddUser" method but then I got a lot of strings flying around in my source code which is not what I want. Or am I overlooking something? Is is possible to use the template from the "GET" route as fallback if no template for the "POST" route was specified?

I asked because the rules were inconsistent between both registrations.

**Comment by gitblit** [comment]
You can manually specify the template:

``` java
Results.html().template("views/AnotherController/anotherview.ftl.html");
```

But I don't know of a way to specify a fallback template.  What's wrong with the redirect?  Too many requests?
