### ISSUE TITLE
Session send_only_if_changed doesn't update timestamp

### ISSUE THREAD

**Issue by NickHirras** [ninjaframework/ninja#374]
When I have application.session.send_only_if_changed=true, the Session cookie doesn't get re-sent with a new timestamp.  Effectively, the user will get logged-out after expire_time_in_seconds regardless of any activity.  

I would like to user to stay logged-in until they have been inactive for expire_time_in_seconds.

When I set send_only_if_changed=false, I get the cookie with a new timestamp at each request, so it looks like the user will stay logged in until expire_time_in_seconds of inactivity.  However, with this configuration, I'm unable to actually log-out of the application by calling context.getSession().clear(); In Chrome I can see the cookie gets removed for the logout request, but clicking another link I get the session cookie re-sent, which keeps me logged-in.  

Is there a bug in the framework, or should the login/logout be handled differently?  I'm using the code from the ninja-servlet-jpa-blog-archetype project.

**Comment by NickHirras** [comment]
I'm on Chrome Version 43.0.2357.130 m on Win 7 64 bit.

Screenshots of dev tools to try and illustrate what I'm seeing.

![image](https://cloud.githubusercontent.com/assets/3911628/8376911/de06002e-1bd1-11e5-9ee6-b96b686e4883.png)

![image](https://cloud.githubusercontent.com/assets/3911628/8376950/4f59e77c-1bd2-11e5-830f-2e0197f19074.png)

**Comment by NickHirras** [comment]
I tried manually clearing all cookies, and first link I click I appear logged-out, then second link I'm logged-in again.

**Comment by raphaelbauer** [comment]
Is this the plain blog archetype you are using? I have to reproduce this somehow to get the problem...

**Comment by NickHirras** [comment]
This is the blog JPA archetype.  Right now my application.conf contains

```
application.cookie.prefix=JST
application.cookie.encryption=true

application.session.expire_time_in_seconds=1800
application.session.send_only_if_changed=true
application.session.transferred_over_https_only=false
```

I've also tried with `application.session.send_only_if_changed=false` which prevents me from being able to actually log out.

**Comment by raphaelbauer** [comment]
That sounds all perfect... One thing does not make sense to me:

```
context.getSession().clear(); In Chrome I can see the cookie gets removed for the logout 
request, but clicking another link I get the session cookie re-sent, which keeps me logged-in.
```

One remark: Technically - if you say context.getSession().clear(); the session is emptied of all values (set application.cookie.encryption=false to watch that). But a session does not imply that you are logged in. Login is usually done by setting something inside the session. If a username is set the user is logged in or something (that's how it's done in the blog archetype).

Second remark: If you get logged in again - what does that mean? The browser is still sending a cookie? Because that may be what you expect...

**Comment by NickHirras** [comment]
I just tested with a fresh project, following the instructions in: http://www.ninjaframework.org/documentation/working_with_relational_dbs/jpa.html

I ran:
`mvn archetype:generate -DarchetypeGroupId=org.ninjaframework -DarchetypeArtifactId=ninja-servlet-jpa-blog-archetype`

![image](https://cloud.githubusercontent.com/assets/3911628/8386587/3e790bbe-1c17-11e5-84d9-b9bca23dcb7a.png)

Then did a:
   mvn compile
   mvn ninja:run

I see the same behavior as in my other project, the timestamp on the cookie stays constant which means I'll get logged-out at that time even if I'm actively using the application.

I tried switching to `application.session.send_only_if_changed=false` but don't see the same issue I was having, I'll keep playing with the settings and see if I can figure out which change is causing my problem.

**Comment by NickHirras** [comment]
I have a `user` object stored in the session, and use it to show the logged-in users account name in the header.  When I click logout, that info disappears, until I click any other link, when the next page is rendered the username is back, as well as the various nav items that are only shown for a logged-in user.  It's weird, not the behavior I was expecting at all.

**Comment by raphaelbauer** [comment]
That's indeed wired...

**Comment by raphaelbauer** [comment]
Maybe there is a race condition between different responses that update the cookie?

**Comment by imnes** [comment]
https://drive.google.com/file/d/0BxrV1XS12N53OGd6aWQ5X18wckE/view?usp=sharing

**Comment by NickHirras** [comment]
It's only happening in Chrome.  I just tried IE and Firefox and it's working fine there.  Really not sure what could be causing it, I have disabled my only plugin but didn't seem to make a different.

**Comment by NickHirras** [comment]
I looked closer at the network log and here's what's happening.  When I click logout, the page comes back and sets my jstwebapp_SESSION="";  Then later the favicon.ico comes back with the previous jstwebapp_SESSION="xxxxxx", which I'm guessing has my logged-in user information, which gets sent back to the server on the next request.

![image](https://cloud.githubusercontent.com/assets/3911628/8387699/56d2c0d4-1c20-11e5-821d-c2251a3221fa.png)

![image](https://cloud.githubusercontent.com/assets/3911628/8387716/8aab4c32-1c20-11e5-9efe-9eae280b4c86.png)

![image](https://cloud.githubusercontent.com/assets/3911628/8387744/d08543ac-1c20-11e5-95a7-59b6e726ce17.png)

Searching for similar problems I came up with this article, similar problem.  

http://allinthehead.com/retro/359/a-favicon-broke-my-app

**Comment by raphaelbauer** [comment]
Very good observation! Yea - we should server a 404 or add a favicon... :) I actually did not know that kind of problem... Computers are strange beasts.... Nice!

**Comment by raphaelbauer** [comment]
That's by the way a race condition of the two requests...

**Comment by NickHirras** [comment]
Weird problem, I think I only triggered it because I changed the catchall route of my app to serve up the 404notfound webpage instead of the main index.  Switching that back and the problem goes away.

Originally it was:

```
    router.GET().route("/.*").with(ApplicationController.class, "index");
```

I had changed that to:

```
    router.GET().route("/").with(ApplicationController.class, "index");
    router.GET().route("/.*").with(Results.html().template("/views/system/404notFound.ftl.html"));
```

I didn't realize that just removing the catchall would serve up exceptions for missing routes, which is what I was trying to achieve.

```
      router.GET().route("/").with(ApplicationController.class, "index");
```

**Comment by chainar** [comment]
So what was the solution for this problem other than reverting catchall routing @imnes. How shiould the race condition be avoided? Can you explain in more detail with reason, the "we should server a 404 or add a favicon" @raphaelbauer.

**Comment by NickHirras** [comment]
I added a favicon to my project, that seems to have fixed it for me.

**Comment by momiji** [comment]
It looks like this is a very specific situation you have here, that only appears with favicon, because the browser is sending the request for favicon in "parallel" with the page request. Here the server receives 2 requests with the same "logged in" cookie, the first one being for the logout page, the other one for the favicon page. It also seems that the response are always in the same order, but this is not something we should rely on: first the logout page, that clears the cookie, then the favicon page, that continues the session from the received cookie. This is why the session nevers logs out.

As you have already noticed, the problem comes from the catch-all route, as it responds with a valid request to the favicon query, but also from the browser, that sends the request in parallel instead of sequentially after receving the logout page response.

I would say there is no technical solution for this, as it's just the way HTTP works.

Some Ideas that comes as-is:
- do not update cookie when favicon is called, but I'm not sure if it is possible, as the icon url may be changed
- remove the catch-all from the artifact to prevent it's use and explain in the documentation why this is a bad idea to have one, unless a favicon is provided (because it is cached by the browser - but this is also something that must be verified)
- maybe update the cookie no more that once every xx seconds, but I can't see how this can be implemented, espacially if multiple servers are used in a cluster, unless we use the timestamp from the cookie itself... don't know, I need to have a look in the code for this
- maybe do not update cookie if the response is an error page ?

Personally, I do vote on number 2, it seemed on my project that we did not have this issue as we removed the catch-all route, but we will definitely add a favicon to prevent all this :)

Mabe a FAQ or sort of documentation can list some good practices and things to do, with reference to the github issue/pr for people who want more in-depth explanation...

Maybe number 3 can also be somthing interesting, but I'm not sure it can work... Imagine we did not send back cookie for 1 minute, then if you wait for 2 minutes then click logout, the problem will still appear...
