### ISSUE TITLE
[Test] NullpointerException during NinjaTest

### ISSUE THREAD

**Issue by ebens** [ninjaframework/ninja#442]
Hi,

I'm getting a NullpointerException when running a Testcase that calls a method which uses Messages.

```
java.lang.NullPointerException
    at ninja.servlet.NinjaServletContext.getCookie(NinjaServletContext.java:270)
    at ninja.i18n.LangImpl.getLanguage(LangImpl.java:108)
    at ninja.i18n.MessagesImpl.getWithDefault(MessagesImpl.java:110)
    at controllers.LocationController.saveLocation(LocationController.java:91)
    at controllers.LocationControllerTest.testThatSaveLocationRedirectsToLocationsIfValidationOkAndSavesLocation(LocationControllerTest.java:121)
```

And thats the testcase

``` java
    @Test
    public void testThatSaveLocationRedirectsToLocationsIfValidationOkAndSavesLocation() {
        Injector applicationInjector = getInjector();
        LocationController controller = applicationInjector.getInstance(LocationController.class);
        LocationDao dao = applicationInjector.getInstance(LocationDao.class);
        Context context = applicationInjector.getInstance(Context.class);
        Validation validation = applicationInjector.getInstance(Validation.class);

        LocationDto dto = new LocationDto();
        dto.setCity("testLocationControllerCity");
        dto.setCountry("testLocationControllerCountry");
        dto.setName("testLocationControllerName");
        dto.setZip("testLocationControllerZip");
        dto.setStreet("testLocationControllerStreet");

        Result result = controller.saveLocation(context, dto, validation); // this is causing the exception

        assertTrue(context.getFlashScope().contains("success"));
        assertTrue(result.getHeaders().get(Result.LOCATION).contains("locations"));

        List<Location> locations = dao.getLocations();
        assertEquals("testLocationControllerName", locations.get(locations.size() - 1).getName());
    }
```

Is there a way to avoid that? I'm not sure whether I setup everything correctly.

Thanks!
Erik

**Comment by raphaelbauer** [comment]
Hey Erik,

that can't work, so it is "ok" that you get a NPE. The reason is that Context (and Validation and your LocationDto) are instances for the request. If you call 

```
applicationInjector.getInstance(Context.class);
```

You get a kind-of-working instance of context, but a lot is missing. That's why you get the NPE.

If you look at the stacktrace you see tha NinjaServletContext.java:270 is:

```
javax.servlet.http.Cookie[] cookies = httpServletRequest.getCookies();
```

That means your Context does not have a httpServletRequest. and that makes sense, because Context is only complete after calling "init". And the DI mechanism knows nothing about that.

A solution depends on your general test setup. But maybe it is better to mock context object (Context.class) yourself. You can then call contextMock.verify(...) to check that all interactions with the mock were correct....

Another option is to use your approach, but call the "init" method and set the httpServletRequest and httpServletResponse. You can use mocks I guess to mock both (but they need at least some behavior).

```
   public void init(ServletContext servletContext,
        HttpServletRequest httpServletRequest,
        HttpServletResponse httpServletResponse) {
```

Or a third option is to call the route via http and test on the real output of your server. Then you don't need any mocking. 

Hope that helps...
