### ISSUE TITLE
Some General Issues Subjecting Documentation

### ISSUE THREAD

**Issue by ghost** [ninjaframework/ninja#454]
I have some suggestions in order to make the documentation a bit more efficient. Please see if those changes are likely to be accepted. Please just take a look and let me know:
- [x] **ADVANCED TOPICS** should get more subsections, in order to shrink (19 entries are really too much)
- [ ] Avoid long menu entries (like **Working with XML**, should become **XML** thus essence is immediately seen)
- [x]  **COMMERCIAL SUPPORT** should move after "GREAT COMMUNITY"
- [ ]  The **Ninja - high level overview** should become graphical (very important, and should be done by the core devs). Additionally rename to **Architecture** or another concise single-word term.
- [ ] The **INTRODUCTION** should start with a **Quick Start** , code & results should be the first thing a visitor sees.
- [ ]  The **Quick-Start** should showcase a **Blog in 15 minutes** (with JPA, and if possible User-Login), demonstrating immediately the "change-something and see it immediately" and other benefits of ninja.
- [ ]  The index page should possibly contain right after **Rock solid, fast, and super productive** something like this: Can't wait? Get a blog app in 20 min <link to Quick Start>

**Comment by raphaelbauer** [comment]
That makes a lot of sense. You are a born marketing genius :)

Commercial support will become a separate site anyway. So there will be support => community support (so, mailing list, github) and commercial support (separate site).

**Comment by lazaridis-com** [comment]
Nah, I just looked at hundreds of sites describing frameworks, and thus I know quite good what works well.

I'm still missing a framework where the website introduces you with a simple app (e.g. blog or issue-tracker) into the framework, and then teaches you how to extend this, whilst introducing further top-level functionality.

Now, anything special I need to know in order to change the navigation of the docs?

**Comment by lazaridis-com** [comment]
(it seems the website gets not updated. But I need to see the changes, in order to take the next steps)

**Comment by lazaridis-com** [comment]
@raphaelbauer , I don't understand. I've asked here prior to making changes, in order to save my time and your time.

Now I saw that you don't merge the change within  #455, which is essential in order to make things better.

"Commercial Support" does **not** belong in a *prominent position* within the menu. It's simply too much, the visitor sees 2 times "Commercial Support", before seeing any code.

You don't need to be a genius to understand this.

Either you delegate some work, or not, but I cannot discuss every tiny (and obvious) change.

**Comment by raphaelbauer** [comment]
Your tone sounds rude. And that's not the way it works here. Having said that - you should consider moving on and finding another project that better suits your style. (@jjlauer)

**Comment by lazaridis-com** [comment]
You sound confused. Please, get serious, and get control of your paranoia (seeing rudeness everywhere except in you).

"Commercial Support" does not belong in a prominent position within the menu. It's simply too much, the visitor sees 2 times "Commercial Support", before seeing any code."

That's a fact, and its a real tragedy if you don't see it.

It's of course your right to not see it and to refuse the change to the documentation. But please, stop your "baby-talk" to me. Find a dog for this.

**Comment by drouillard** [comment]
'Please, get serious, and get control of your paranoia' - That is rude.
'That's a fact, and its a real tragedy if you don't see it.' -  Mostly arrogant - still rude though.
'But please, stop your "baby-talk" to me.' That is rude.
'Find a dog for this.' - Also good for playing fetch and taking on walks. I approve of this one.

**Comment by raphaelbauer** [comment]
Thanks for taking sides! After a careful discussion the Ninja lead team decided to block the account. And that's the quick end of the story. It's for sure a good and competent person, but the style is not compatible with this community.

**Comment by lazaridis-com** [comment]
tst

**Comment by lazaridis-com** [comment]
@drouillard , you're clearly out of your league here, so please, crawl away.

@raphaelbauer , @jjlauer - the play documentation is in a terrible condition. I personally cannot use it to make a teach-in. Thus I posted the plan, and (after getting the ok) I posted some change-requests (PR's).

It's one thing if you don't respect my time, it's another one if you don't respect your userbase. You don't respect them, because you're blocking contributions which would totally(!) obvious(!) benefit the quality of the documentation.

So, you **owe** it to your userbase (and to potential users) to overcome yourselves. Stop being that rude to ask contributors to become "compatible with you" (this is **very** **very** rude), and start to be more tolerant.

If you fail to do so with me, then at least do it with future contributors. Look at the contributed stuff, and know when to be silent and stop micro-management.

Otherwise you'll never be able to compete with the big framework players of the jvm domain.

**Comment by drouillard** [comment]
@lazaridis your own site looks like garbage and still uses iframes for
navigation. You don't have a repo with over 2 stars. Yet act as if you have
total confidence in yourself. You are an imposter and you should so go
away. Build something that has as many users and ninja and then you can
come back here and give advice.

**Comment by lazaridis-com** [comment]
@drouillard please, crawl (I've not read you reply, it's simply irrelevant).

**Comment by drouillard** [comment]
I have said my peace.  At this point everyone can move on.
