### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by saharabear** [ninjaframework/ninja#492]
Any good way to add WebSocket support in Ninja project?

I have tried to use servlet in ServletModule, but when I add the following code to pom.xml, ninja stopped working.

```
    <dependency>
      <groupId>javax.websocket</groupId>
      <artifactId>javax.websocket-api</artifactId>
      <version>1.0</version>
    </dependency>
    <!-- To run javax.websocket in embedded server -->
    <dependency>
      <groupId>org.eclipse.jetty.websocket</groupId>
      <artifactId>javax-websocket-server-impl</artifactId>
      <version>${jetty-version}</version>
    </dependency>
    <!-- To run javax.websocket client -->
    <dependency>
      <groupId>org.eclipse.jetty.websocket</groupId>
      <artifactId>javax-websocket-client-impl</artifactId>
      <version>${jetty-version}</version>
    </dependency>
```

Any suggestions? Thanks.

**Comment by jjlauer** [comment]
Hi Haulyn,

No built-in support for websockets yet.  It's becoming a more popular
question on the mailing list, so its probably a matter of time.

Ninja is a community effort, so if you were interested in adding support
for it, I know many of the more active Ninja folks would be happy to help
review your proposal/PRs.

I took a look about a month ago to see how websockets would work in
ninja-undertow (a non-servlet based container)(
https://github.com/fizzed/ninja-undertow).

I suspect want to provide hooks into controller methods for setting up
websockets, then some sort of specialized controller method for message
handling.  Since Ninja isn't tied to servlets specifically, we'd probably
need to think about how the main Context object can allow enabling support
for websockets, depending on the final bound Context implementation.  If
you look at ninja-servlet, you'll see how its ServletContextImpl actually
is what does the heavy lifting when Ninja runs in a servlet container.
Alternatively, you can see how a non-servlet Context works here
https://github.com/fizzed/ninja-undertow/blob/master/ninja-undertow/src/main/java/ninja/undertow/NinjaUndertowContext.java

So, websockets would be an awesome feature, but it definitely will hit much
of the core code.

-Joe

**Comment by saharabear** [comment]
Thanks very much, I will fork ninja and deep in the source code to find more.
