### ISSUE TITLE
Improve Validation

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#549]
Complexity: Large

There are a lot of things in validations that may need a cleanup. For instance Validation object hasBeanViolation and hasFieldViolation. That does sounds strange. Is there a better way to do this?
There may be other obstacles on the way as Validation is a very old class with a legacy.

**Comment by jlannoy** [comment]
Hi @raphaelbauer.

I can take at least this one enhancement, if you agree.

I propose to remove the two concepts of « beanViolation » and « fieldViolation ». The « validation » handler would reference the existing « ConstraintViolation » object, containing (unchanged) :

- field
- messageKey
- defaultMessage
- messageParams[]

The validation handler would expose the following methods :

- boolean hasViolations()
- boolean hasViolations(field)
- void addViolation(ConstraintViolation) *
- List<ConstraintViolation> getViolations()
- List<ConstraintViolation> getViolations(field)

* Already exists but deprecated for a long time now. It was used for « general violations ». But it would be cleaner with that name.

All other existing methods are kept as deprecated, with a backward compatible implementation. The beanViolation would be recognized based on the hibernate prefixed message key. The documentation would only show the 5 methods listed before.

Other proposed changes :

- The JSRValidator should also be modified. Today it returns the interpolated (translated) message inside the message key, with no default message. It’s not consistent with all other validation and should be changed. The same key as hibernate would be used, without the brackets.
- The « validation » object could be added automatically to html templates (always, we don’t care if it’s empty). What do you think?
- We should provide a Freemarker method that write the message corresponding to the ConstraintViolation, that would look after a translation based on the given key, and use the default message as… a default message.
- I faced a bug in a project where we couldn’t use our own validation annotations library, due to the fact that our message properties inside that library where not found or used by the JSRValidator. I would try to fix that.

**Note that it would made a lot of deprecated code and tests (2/3). I think it’s important to plan a removal of all that deprecated code at a certain time.**

Do you see (an) other thing(s) that would be cool to refactor?

In a second time, I can study how (and why) we would update to hibernate validator 5.4 (spec Bean Validation 1.1) ; but I think it can be done a little bit later.

**Comment by raphaelbauer** [comment]
This makes a lot of sense. Very good write-up.

Regarding unifying fieldViolation / beanViolation (they are broken anyway right now). Would it be possible to mix them like

    public Result registerUser(@MustBeLoggedIn String user, @JSR303Validation PasswordForm    
        passwordForm, Validation validation) { .. } 
?

Where PasswordForm looks like

    class PasswordForm {
        @AnyValidation String user;
    }

How would I check violations for user and passwordForm.user?

You are using the validation right now in your live apps - right? To be honest - I do not use validation right now in my apps because it was a lot simpler to implement validation myself, so I am not the gold standard here :)

But to cut things short: If you use it yourself I'd totally trust what you are doing. Plus - the things you proposed make a lot of sense to me :)

@jjlauer Sounds good to you, too?

**Comment by jlannoy** [comment]
Yes, we are using validation in live apps. It's why I'm interested to make it better, or at least easier. I'm interested in making the enhancement related to Optional parameters in controller methods too, proposed by Joe.

For your question about "user", I did not see such a use case. But thinking about it... According to me the controller method is badly written in such case. Think to the request received. Actually with Ninja, you can not have a string "user" coming from url parameters and an other string "user" coming from request body. The url one (path or not) is taken first. So if we want to allow two validation cases, we should do some refactoring to be sure that the BodyParser only takes from the request body, and the parameters from the right place. Am I wrong on this? I didn't check the source code, but I did some tests that were going this way.

**Comment by jjlauer** [comment]
Plan looks good to me, although I may only have more feedback after trying
out the changes in our own apps.  The different validations have always
been confusing to me (bean vs. field).  We use JSR303Validation for all our
form objects so we use it a lot in our apps.

**Comment by raphaelbauer** [comment]
@jlannoy Regarding the "user" example above - I agree - that is bad design. The only thing that then comes to my mind is to throw an exception (afaics when starting the app and compiling the routes) that there is a conflict.

Everything else sounds awesome.

Looking forward to your contribution! Let us know if we can help in any way :)
