### ISSUE TITLE
Empty testcase waiting for removal

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#598]
https://github.com/ninjaframework/ninja/blob/3a9f02bd32a3963f2dd8b0996e951253797a5456/ninja-metrics/src/test/java/ninja/metrics/InstrumentedCacheTest.java#L25

**Comment by raphaelbauer** [comment]
Thanks for the fix!

**Comment by bacriom** [comment]
:)

El 18/12/2017 3:06 p.m., "Raphael A. Bauer" <notifications@github.com>
escribió:

Thanks for the fix!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ninjaframework/ninja/issues/598#issuecomment-352557475>,
or mute the thread
