### ISSUE TITLE
ninja Archetype IT 'basic' failed: Cannot run additions goals in 6.4.2

### ISSUE THREAD

**Issue by gilbertguan2385** [ninjaframework/ninja#657]
maven(version 3.5.4) build command is `mvn clean install -DskipTests` using jdk1.8 under windows OS
and result in 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration-test) on project ninja-servlet-jpa-blog-archetype:
[ERROR] **Archetype IT 'basic' failed: Cannot run additions goals.**
[ERROR] -> [Help 1]
```
inspite of exclude archetype modules,how can I successfully build source ?

**Comment by thibaultmeyer** [comment]
Hello,

This error is due to the `maven-archetype-plugin` plugin on Windows causes problems when it try to invoke `mvn` command. Link to the issue: https://issues.apache.org/jira/browse/ARCHETYPE-488.

You have to upgrade your Maven version and upgrade the dependency `maven-archetype-plugin` to the latest version.

```xml
<dependency>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-archetype-plugin</artifactId>
    <version>3.2.1</version>
</dependency>
```
